Add a fix for Rails 6 HTML rendering.
dradis/dradis-html_export pull request #39
Opened 2021-01-21 07:03 UTC by sean-yeoh

### Summary

This PR adds a fix for Rails 6 not rendering html erb files outside the `app/views` directory.
It is achieved by copying the original html.erb to a tmp folder inside the `app/views` directory then removing the folder after processing.

### Copyright assignment
Collaboration is difficult with commercial closed source but we want
to keep as much of the OSS ethos as possible available to users
who want to fix it themselves.

In order to unambiguously own and sell Dradis Framework commercial
products, we must have the copyright associated with the entire
codebase. Any code you create which is merged must be owned by us.
That's not us trying to be a jerks, that's just the way it works.

Please review the [CONTRIBUTING.md](https://github.com/dradis/dradis-ce/blob/master/CONTRIBUTING.md)
file for the details.

You can delete this section, but the following sentence needs to
remain in the PR's description:

> I assign all rights, including copyright, to any future Dradis
> work by myself to Security Roots.

2021-01-21 14:00 UTC, brianp requested changes

2021-01-21 14:00 UTC, brianp commented on app/controllers/dradis/plugins/html_export/base_controller.rb
> +          exporter.remove_tmp_folder
Feels weird that the tmp folder is created within the exporter process but we're calling the cleanup after the fact.

I think if we're creating the folder within the scope of the export, then we should perform the cleanup with the same scope.

2021-01-21 14:00 UTC, brianp commented on spec/lib/dradis/plugins/html_export/exporter_spec.rb
> +      )
Will `file_fixture` or another helper path work here?

2021-01-22 06:07 UTC, sean-yeoh commented on spec/lib/dradis/plugins/html_export/exporter_spec.rb
> +      )
Hmm i tried `file_fixture(''template.html.erb"` but it doens't work. I'm guessing that it's cause the spec is running in the context of the app, running `file_fixture` in the engine spec will return `Rails.root.join('spec/fixtures/files')`.

But i changed it as below so it looks cleaner.
```ruby
Dradis::Plugins::HtmlExport::Engine.root.join(
  'spec/fixtures/files/template.html.erb'
)
```

2021-01-22 06:10 UTC, sean-yeoh commented on app/controllers/dradis/plugins/html_export/base_controller.rb
> +          exporter.remove_tmp_folder
Yeah much better. I'll move it in the exporter function. Forgot that i can assign a variable to the html. :facepalm:

2021-01-25 08:56 UTC, brianp commented on lib/dradis/plugins/html_export/exporter.rb
> +          destination_path = Rails.root.join("app/views/tmp/templates/html_export/#{filename}")
I see two issues with this directory:

- If we're creating a special `tmp` dir do we need the `templates/html_export/file` structure inside it. Or can't we just do `tmp/file`?
- We're removing the entire `tmp` directory to cleanup the template. This is not safe for parallel executions. If User A starts a report export, then User B begins one we have the potential for the cleanup of A to wipe out B's template. I think we have to leave the /tmp/ dir and only remove the files with it or something similar.

2021-01-25 09:03 UTC, sean-yeoh commented on lib/dradis/plugins/html_export/exporter.rb
> +          destination_path = Rails.root.join("app/views/tmp/templates/html_export/#{filename}")
`tmp/file` works just as fine. I just thought being explicit makes more sense.

> If User A starts a report export, then User B begins one we have the potential for the cleanup of A to wipe out B's template.

Hmm, i haven't thought of this. I think this will also occur If user A and user B uses the same template right? Would it work if i add a timestamp to the file? E.g. `tmp/template-1611565401092.html.erb`, this way there's _less_ potential for a collision

2021-01-25 09:09 UTC, brianp commented on lib/dradis/plugins/html_export/exporter.rb
> +          destination_path = Rails.root.join("app/views/tmp/templates/html_export/#{filename}")
> I think this will also occur If user A and user B uses the same template right?

Any templates. Because `remove_dir` removes the entire directory right now. It'll remove the entire `tmp` folder and everything in it.

> remove_dir(path, force = false)
Removes a directory dir and its contents recursively. This method ignores StandardError if force is true.

If we persist the tmp dir, then you are also correct. Even if a user is using the same template we risk removing it unless each tmp file is uniquely named.

You should use [Ruby's stdlib](https://ruby-doc.org/stdlib-2.7.2/libdoc/tempfile/rdoc/Tempfile.html) `Tempfile` for uniqueness in the process. You can assign the directory the file is created in.

2021-01-25 09:22 UTC, sean-yeoh commented on lib/dradis/plugins/html_export/exporter.rb
> +          destination_path = Rails.root.join("app/views/tmp/templates/html_export/#{filename}")
> You should use Ruby's stdlib Tempfile for uniqueness in the process. You can assign the directory the file is created in.

Thanks! Using Tempfile's much better.

2021-01-26 12:13 UTC, brianp commented on lib/dradis/plugins/html_export/exporter.rb
>          end
I don't think this method is used anymore.

2021-01-26 13:27 UTC, sean-yeoh commented on lib/dradis/plugins/html_export/exporter.rb
>          end
Removed

2021-02-01 16:59 UTC, etdsoft commented
There's a lot going on here... I don't necessarily like the approach and would rather we took the hit on moving to Liquid pronto!

That being said in pseudo code:
1. create template (via copy)
2. use template
3. delete template

Looks like a nice candidate for `yield` / around / `ensure`?

Also there's something about building our own filename that I don't fully like 

https://stackoverflow.com/questions/13787746/creating-a-thread-safe-temporary-file-name

2021-02-02 14:06 UTC, sean-yeoh commented
> There's a lot going on here... I don't necessarily like the approach and would rather we took the hit on moving to Liquid pronto!

Yeah i agree, i don't like it as well but it's the most elegant solution for now. Will tackle liquid another time :v:

2021-02-03 15:04 UTC, etdsoft commented
🤦‍♀️ I think I didn't explain myself

```ruby
 def with_temporary_template(original, &block)
  # create temp file
  # yield for render
    yield(template_name)
  ensue
  # delete temp file
end
```

And then have the `#export()` be something like:

```ruby
with_temporary_template(original_template) do |temporary_template|
  controller.render(
    template: temporary_template,
    #...
end
```

(method and variable names of your choice)

With that implementation you neatly hide the complexity of copying the template and cleaning up within a private method of the Exporter class.

2021-02-04 15:27 UTC, merged